# Introduction to Programming Artificial Intelligence 

## Class 6 - Exceptions and NumPy ndarray

### Exercise 1

The following code iterates over a list of words and assigns a fifth letter of each word to the new list fifth_letter. The current version of the code produces an exception. Your task is to include a try/except clause that will allow the code to run and produce a list of the fifth letter in each word, only for the words that are long enough.

In [1]:
words = ["chocolate", "chicken", "soup", "potatoes", "beef", "lox", "beef"]
fifth_letter = []
for w in words:
    try:
        fifth_letter.append(w[4])
    except IndexError as error:
        print("Index Error")
    
    
print(fifth_letter)

Index Error
Index Error
Index Error
Index Error
['o', 'k', 't']


### Exercise 2
The following function is suppose to safely return the element specified by the index from a list of values – i.e., if the index is outside the bounds of the list, it should return the constant None. At the moment, it generates an error. Include a try/except clause to handle the error.

In [2]:
def get_value(values, index):
    try:
        return values[index]
    except IndexError as error:
        return print("Index Error")

# sample list data
my_list = ['a', 'b', 'c']
print(get_value(my_list, 1))
print(get_value(my_list, 4))

b
Index Error
None


### Exercise 3 
Write a function called batch_log that calculates and prints the log base 10 value for each element of a list passed as parameter. Use exception handling to skip the calculation of any value that produces an error.

In [3]:
# import math library (required for log function)
import math
# write your function here – use math.log() to calculate the log value
def batch_log(n):
    for num in n:
        try:
            print(math.log10(num))
        except:
            print("Error: calculation skipped")

values = [0.8, -0.1, 0.9, -0.1, 0.1, 0.300000000004, -0.1, 0.5, 1.0, -0.1,
0.9, 0.9, 0.1, 1.0, 0.2, 0.2, 0.1, 0.9, 0.0, 1.0]
batch_log(values)

-0.09691001300805639
Error: calculation skipped
-0.045757490560675115
Error: calculation skipped
-1.0
-0.5228787452745469
Error: calculation skipped
-0.3010299956639812
0.0
Error: calculation skipped
-0.045757490560675115
-0.045757490560675115
-1.0
0.0
-0.6989700043360187
-0.6989700043360187
-1.0
-0.045757490560675115
Error: calculation skipped
0.0


### Exercise 4
Consider the following implementation of an Account class and a withdraw method. create a custom exception type name InsufficientBalanceError and modify the code to raise this type of exception every time there is an attempt to withdraw a value greater than the current available balance:

In [4]:
# define Python user-defined exceptions
class Error(Exception):
    pass

class InsufficientBalanceError(Error):
    pass

class Account:
    def __init__(self, number, balance):
        self.number = number
        self.balance = balance
    
    def withdraw(self, value):
        # TODO: withdraw cannot happen if value is greater than balance
        try:
            if(value > self.balance):
                raise InsufficientBalanceError
            else:
                self.balance -= value
        except InsufficientBalanceError:
            print("ERROR: This value is too large, try again!")

# sample code
account = Account("1000", 100)
account.withdraw(200)

ERROR: This value is too large, try again!


### Exercise 5
Create a NumPy multidimensional array (10 rows x 5 columns) with random values.

In [5]:
import numpy as np
data = np.random.randn(10,5) # 10 random numbers' array

print(data)

[[-0.99388151  0.55749047 -0.02507538 -1.23914866  0.33046598]
 [ 0.21182278  2.01907207 -0.38339718  0.88618678  0.82399107]
 [-0.07271404  0.1936452   0.05796381 -0.38767002 -0.11092428]
 [ 0.1309269   0.1755817   0.13282698 -1.35911098 -0.02180102]
 [-2.31037508  0.80335168 -0.88715005 -0.38771659 -0.27924618]
 [ 1.4679023  -0.23324138  0.12416764 -0.30534919 -0.23015475]
 [ 0.95238113  0.25400051  1.11242934  0.05858001 -1.03463969]
 [ 0.44329586 -2.23508418 -1.91289208 -1.43346525  0.93814131]
 [-0.45177961  0.40142646 -0.06040392  0.3210529  -0.03603092]
 [-1.28472869  0.48375     0.08299786  1.23982906 -0.60465929]]


### Exercise 6
Using the array created in (5), write a function that returns the index of the row with the highest mean value.

In [10]:
def return_max_row(n):
    maxValues = n.max(axis = 1)
    max_value=-math.inf

    for num in maxValues:
        if(num > max_value):
                value = num
    return value

return_max_row(data)

1.2398290600807063

### Exercise 7
Using the array created in (5), write a function that returns the index of the column with the highest mean value.

In [11]:
def return_max_column(n):
    maxValues = n.max(axis = 0)
    max_value=-math.inf

    for num in maxValues:
        if(num > max_value):
                value = num
    return value

return_max_column(data)

0.9381413139478954

### Exercise 8
Using the array create in (5), write a function that return a tuple (row, column)
representing the indexes of the row and column of the maximum value in the array.

In [ ]:
import numpy as np
def calculate_max(n):
    row,column = np.where(n == n.max())
    return row[0], column[0]

calculate_max(data)

In [ ]:
data.shape # returns the dimension of the 2D array

In [ ]:
import math
def calculate_max_new(n):
    max_value=-math.inf
    for row in range(n.shape[0]):
        for column in range(n.shape[1]):
            if(n[row][column] > max_value):
                max_value = n[row][column]
                atuple=(row,column)
    return atuple

calculate_max_new(data)